version: '3.8'

services:
  weather-app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile to use
      args:
        API_KEY: ${API_KEY} # Load the API_KEY from the .env file
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    restart: always # Restart the container automatically if it stops